/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as ProduccionAudiovisualRouteImport } from './routes/produccion-audiovisual'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as BcapstudioRouteImport } from './routes/bcapstudio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiciosVideoCorporativoRouteImport } from './routes/servicios.video-corporativo'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduccionAudiovisualRoute = ProduccionAudiovisualRouteImport.update({
  id: '/produccion-audiovisual',
  path: '/produccion-audiovisual',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const BcapstudioRoute = BcapstudioRouteImport.update({
  id: '/bcapstudio',
  path: '/bcapstudio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosVideoCorporativoRoute =
  ServiciosVideoCorporativoRouteImport.update({
    id: '/video-corporativo',
    path: '/video-corporativo',
    getParentRoute: () => ServiciosRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bcapstudio': typeof BcapstudioRoute
  '/booking': typeof BookingRoute
  '/contacto': typeof ContactoRoute
  '/produccion-audiovisual': typeof ProduccionAudiovisualRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/servicios/video-corporativo': typeof ServiciosVideoCorporativoRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bcapstudio': typeof BcapstudioRoute
  '/booking': typeof BookingRoute
  '/contacto': typeof ContactoRoute
  '/produccion-audiovisual': typeof ProduccionAudiovisualRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/servicios/video-corporativo': typeof ServiciosVideoCorporativoRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bcapstudio': typeof BcapstudioRoute
  '/booking': typeof BookingRoute
  '/contacto': typeof ContactoRoute
  '/produccion-audiovisual': typeof ProduccionAudiovisualRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/servicios/video-corporativo': typeof ServiciosVideoCorporativoRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bcapstudio'
    | '/booking'
    | '/contacto'
    | '/produccion-audiovisual'
    | '/servicios'
    | '/sitemap.xml'
    | '/sobre-nosotros'
    | '/servicios/video-corporativo'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bcapstudio'
    | '/booking'
    | '/contacto'
    | '/produccion-audiovisual'
    | '/servicios'
    | '/sitemap.xml'
    | '/sobre-nosotros'
    | '/servicios/video-corporativo'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/bcapstudio'
    | '/booking'
    | '/contacto'
    | '/produccion-audiovisual'
    | '/servicios'
    | '/sitemap.xml'
    | '/sobre-nosotros'
    | '/servicios/video-corporativo'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BcapstudioRoute: typeof BcapstudioRoute
  BookingRoute: typeof BookingRoute
  ContactoRoute: typeof ContactoRoute
  ProduccionAudiovisualRoute: typeof ProduccionAudiovisualRoute
  ServiciosRoute: typeof ServiciosRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produccion-audiovisual': {
      id: '/produccion-audiovisual'
      path: '/produccion-audiovisual'
      fullPath: '/produccion-audiovisual'
      preLoaderRoute: typeof ProduccionAudiovisualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bcapstudio': {
      id: '/bcapstudio'
      path: '/bcapstudio'
      fullPath: '/bcapstudio'
      preLoaderRoute: typeof BcapstudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/video-corporativo': {
      id: '/servicios/video-corporativo'
      path: '/video-corporativo'
      fullPath: '/servicios/video-corporativo'
      preLoaderRoute: typeof ServiciosVideoCorporativoRouteImport
      parentRoute: typeof ServiciosRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServiciosRouteChildren {
  ServiciosVideoCorporativoRoute: typeof ServiciosVideoCorporativoRoute
}

const ServiciosRouteChildren: ServiciosRouteChildren = {
  ServiciosVideoCorporativoRoute: ServiciosVideoCorporativoRoute,
}

const ServiciosRouteWithChildren = ServiciosRoute._addFileChildren(
  ServiciosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BcapstudioRoute: BcapstudioRoute,
  BookingRoute: BookingRoute,
  ContactoRoute: ContactoRoute,
  ProduccionAudiovisualRoute: ProduccionAudiovisualRoute,
  ServiciosRoute: ServiciosRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
